const copy = {
  en: {
    headline: 'Draft legends. Duel friends. Climb ranks.',
    supportLine: 'A Counter-Strike draft arena — solo or with friends.',
    play: 'Play now',
    windows: 'Windows',
    windowsHint: 'Download the desktop app',
    support: 'Support the project',
    report: 'Submit a report',
    docs: 'Docs',
    readDocs: 'Read the docs',
    modesTitle: 'Six ways to play',
    modesBlurb: 'Each mode has its own rules — not just a different name.',
    modes: {
      major: { title: 'The Major', blurb: 'Real 8-team MD3. The serious one.' },
      duel: { title: 'Knife Fight', blurb: 'BO1 ban war vs BOT or a friend' },
      party: { title: 'Power Party', blurb: 'Same scouts — highest vibes (power) wins' },
      box: { title: 'Box Battle', blurb: 'Queue up to 10 real CS cases. Best pulls win.' },
      daily: { title: 'Blind Daily', blurb: 'Global seed, hidden ratings, BO1 bracket' },
      gauntlet: { title: 'Chaos Gauntlet', blurb: 'Survive BO1 waves with cursed modifiers' },
    },
    disclaimer: 'Not affiliated with Valve or HLTV.',
    lang: 'PT',
    langAria: 'Language',
    reportMailSubject: 'CS4FUN report',
    reportMailBody: 'Type: bug / suggestion / other\n\nDescribe:\n',
  },
  pt: {
    headline: 'Monte lendas. Duele com amigos. Suba no ranking.',
    supportLine: 'Arena de draft de Counter-Strike — solo ou com amigos.',
    play: 'Jogar agora',
    windows: 'Windows',
    windowsHint: 'Baixar o app desktop',
    support: 'Apoiar o projeto',
    report: 'Enviar um relatório',
    docs: 'Documentação',
    readDocs: 'Ler a documentação',
    modesTitle: 'Seis formas de jogar',
    modesBlurb: 'Cada modo tem regras próprias — não é só outro nome.',
    modes: {
      major: { title: 'O Major', blurb: 'MD3 de 8 times de verdade. O sério.' },
      duel: { title: 'Briga de Faca', blurb: 'Guerra de bans BO1 vs BOT ou amigo' },
      party: { title: 'Power Party', blurb: 'Mesmos scouts — maior vibe (poder) vence' },
      box: { title: 'Box Battle', blurb: 'Monte até 10 cases reais do CS. Melhores drops vencem.' },
      daily: { title: 'Diário Cego', blurb: 'Seed global, ratings ocultos, chave BO1' },
      gauntlet: { title: 'Gauntlet do Caos', blurb: 'Sobreviva a ondas BO1 com modificadores amaldiçoados' },
    },
    disclaimer: 'Não afiliado à Valve ou HLTV.',
    lang: 'EN',
    langAria: 'Idioma',
    reportMailSubject: 'Relatório CS4FUN',
    reportMailBody: 'Tipo: bug / sugestão / outro\n\nDescreva:\n',
  },
}

export default copy
