const copy = {
  en: {
    headline: 'Draft legends. Duel friends. Climb ranks.',
    supportLine: 'A Counter-Strike draft arena — solo or with friends.',
    play: 'Play now',
    windows: 'Windows',
    windowsHint: 'Download the desktop app',
    support: 'Support the project',
    report: 'Submit a report',
    docs: 'Docs',
    readDocs: 'Read the docs',
    modesTitle: 'Five ways to play',
    modesBlurb: 'Pick a mode. Build a five. See who wins.',
    modes: {
      major: { title: 'Major Run', blurb: 'Draft a dream five, win the bracket' },
      duel: { title: '1v1 Duel', blurb: 'Shared rolls vs CPU or a friend' },
      party: { title: 'Party Race', blurb: 'Same scouts — highest power wins' },
      daily: { title: 'Daily Challenge', blurb: 'One global seed. Worldwide ranks' },
      gauntlet: { title: 'Gauntlet', blurb: 'Survive escalating BO1 waves' },
    },
    disclaimer: 'Not affiliated with Valve or HLTV.',
    lang: 'PT',
    langAria: 'Language',
    reportMailSubject: 'cs4fun report',
    reportMailBody: 'Type: bug / suggestion / other\n\nDescribe:\n',
  },
  pt: {
    headline: 'Monte lendas. Duele com amigos. Suba no ranking.',
    supportLine: 'Arena de draft de Counter-Strike — solo ou com amigos.',
    play: 'Jogar agora',
    windows: 'Windows',
    windowsHint: 'Baixar o app desktop',
    support: 'Apoiar o projeto',
    report: 'Enviar um relatório',
    docs: 'Documentação',
    readDocs: 'Ler a documentação',
    modesTitle: 'Cinco formas de jogar',
    modesBlurb: 'Escolha um modo. Monte o time. Veja quem vence.',
    modes: {
      major: { title: 'Major', blurb: 'Monte o time dos sonhos e vença o chaveamento' },
      duel: { title: 'Duelo 1v1', blurb: 'Revelações iguais vs CPU ou amigo' },
      party: { title: 'Party', blurb: 'Mesmos scouts — maior poder vence' },
      daily: { title: 'Desafio Diário', blurb: 'Uma seed global. Ranking mundial' },
      gauntlet: { title: 'Gauntlet', blurb: 'Sobreviva a ondas BO1 crescentes' },
    },
    disclaimer: 'Não afiliado à Valve ou HLTV.',
    lang: 'EN',
    langAria: 'Idioma',
    reportMailSubject: 'Relatório cs4fun',
    reportMailBody: 'Tipo: bug / sugestão / outro\n\nDescreva:\n',
  },
}

export default copy
